### ISSUE TITLE
Feature Request: Add video-meter / data-levels into the scene view

### ISSUE THREAD

**Issue by barkermn01** [steveseguin/obsninja#1120]
So i have some custom CSS that works perfectly when i use the normal room access, however when i try and do it in scene version ?scene&room... because the div with the video-meter dot is not in the components it wont work and i can seem to find any way to enable it. this is my custom CSS (and i know it's hacky and horrible that's because OBS's stupid stance on not allowing JavaScript in the browser component)

```css
.container_holder_video:has(.video-meter:not([data-level="0"])):after {
    background-image:url(https://s3.eu-west-1.amazonaws.com/tsunamods.public/dnd-frame-active.png);
}

body { background-color: rgba(0, 0, 0, 0); margin: 0px auto; overflow: hidden; }
.container_holder_video{
    width: 100%;
    height: 100%;
    z-index: 1;
    position: absolute;
}
.container_holder_video:after{
    background-image:url(https://s3.eu-west-1.amazonaws.com/tsunamods.public/dnd-frame.png);
    background-size: 90% 100%;
    content: "";
    position: absolute;
    display: inline-block;
    top:0px;
    leftl:0px;
    width:110%;
    height:110%;
    margin-top:-1%;
    margin-left:-5%;
    background-repeat:no-repeat
}
.container_holder_video {
    padding:10px
}

.holder {
    z-index: 0;
}

.container_holder_video video {
    margin-top: 35px;
    height:98% !important;
}
```
